//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FileArchivingEntities : DbContext
    {
        public FileArchivingEntities()
            : base("name=FileArchivingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adnnin> adnnin { get; set; }
        public DbSet<contact> contact { get; set; }
        public DbSet<pricing1tb> pricing1tb { get; set; }
        public DbSet<pricing250> pricing250 { get; set; }
        public DbSet<pricing4tb> pricing4tb { get; set; }
        public DbSet<userfiles> userfiles { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<whyus> whyus { get; set; }
    }
}
