//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pricing250
    {
        public int id { get; set; }
        public string subscription { get; set; }
        public string payment { get; set; }
    }
}
