//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.userfiles = new HashSet<userfiles>();
        }
    
        public int id { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public Nullable<int> premium { get; set; }
    
        public virtual ICollection<userfiles> userfiles { get; set; }
    }
}
