//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userfiles
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public double size { get; set; }
        public string date { get; set; }
        public string filepath { get; set; }
    
        public virtual users users { get; set; }
    }
}
